# Generated by Django 5.2 on 2025-04-16 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('cuil', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('total_remuneracion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_descuento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_liquido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recibos.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('rem', 'Remuneración'), ('desc', 'Descuento')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recibos.recibo')),
            ],
        ),
    ]
