# Generated by Django 5.2 on 2025-04-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='total_descuento',
            new_name='liquido',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cuil',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='total_liquido',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='total_remuneracion',
        ),
        migrations.AddField(
            model_name='empleado',
            name='centro_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='reduccion_pav',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recibo',
            name='rem_c_aporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recibo',
            name='rem_s_aporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recibo',
            name='rol',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibo',
            name='salario_familiar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recibo',
            name='mes',
            field=models.CharField(max_length=20),
        ),
    ]
