# Generated by Django 5.2 on 2025-04-18 01:15

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies = [
        ('recibos', '0002_previous_migration'),
    ]

    operations = [
        migrations.RemoveField(model_name='Recibo', name='cargo'),
        migrations.AddField(
            model_name='Empleado',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    migrations.AddField(
            model_name='Empleado',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='Recibo',
            name='created_at',
            field=models.DateTimeField(null=True),  # Temporarily allow null
        ),
        migrations.RunSQL(
            "UPDATE recibos_recibo SET created_at = '2025-04-17 12:00:00' WHERE created_at IS NULL",
            reverse_sql="UPDATE recibos_recibo SET created_at = NULL",
        ),
        migrations.AlterField(
            model_name='Recibo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='Recibo',
            name='dias_trabajados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
    operations = [
        migrations.RemoveField(
            model_name='recibo',
            name='cargo',
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibo',
            name='dias_trabajados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='monto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='recibos.recibo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='centro_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_alta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='liquido',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='reduccion_pav',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='rem_c_aporte',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='rem_s_aporte',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='rol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='salario_familiar',
            field=models.FloatField(default=0.0),
        ),
    ] 
